#         ____           _          __     ___      _               _     __  __            _     _ _              _       _     _
#  _   _ / ___|_ __ __ _| |_ ___  __\ \   / (_)_ __| |_ _   _  __ _(_)___|  \/  | ___   ___| |__ (_) | __ _ ___   / \   __| | __| | ___  _ __
# | | | | |   | '__/ _` | __/ _ \/ __\ \ / /| | '__| __| | | |/ _` | / __| |\/| |/ _ \ / __| '_ \| | |/ _` / __| / _ \ / _` |/ _` |/ _ \| '_ \
# | |_| | |___| | | (_| | ||  __/\__ \\ V / | | |  | |_| |_| | (_| | \__ \ |  | | (_) | (__| | | | | | (_| \__ \/ ___ \ (_| | (_| | (_) | | | |
#  \__, |\____|_|  \__,_|\__\___||___/ \_/  |_|_|   \__|\__,_|\__,_|_|___/_|  |_|\___/ \___|_| |_|_|_|\__,_|___/_/   \_\__,_|\__,_|\___/|_| |_|
#  |___/
#

general:
  # Delay de abertura automática
  # em segundos
  automatic-delay: 10

# Sistema de upgrade
upgrades:
  storage-limit:
    # Máximo de limite de keys
    maximum: 4000
    # Limite de keys armazenadas por padrão
    default: 500
    # Quantidade que será acrescida a cada upgrade
    per-upgrade-add: 500
    prices-per-upgrade:
      price1:
        provider: 'money'
        amount: 200.0
  open-limit:
    # Máximo de quantidade de abertura de keys por vez
    maximum: 100
    # Quantidade padrão de abertura de keys por vez
    default: 10
    # Quantidade que será acrescida a cada upgrade
    per-upgrade-add: 10
    prices-per-upgrade:
      price1:
        provider: 'money'
        amount: 200.0

# Item da mochila
backpack:
  material: 'ENDER_CHEST'
  name: '&6Mochila de Chaves'
  lore:
    - '&7Esta mochila armazena todas'
    - '&7as chaves recebidas.'
    - ''
    - ' &6Armazenamento:'
    - ' &7{actual}/{total} {progressbar} &8{percentage}'
    - ''
    - '&6Clique para acessar.'

# Item do abridor automático
automatic:
  material: 'STONE_BUTTON'
  name: '&dAbertura automática'
  lore:
    - '&7Utilize este item para'
    - '&7ativar a abertura das chaves'
    - '&7de forma automática.'
    - ''
    - '&7Arraste em uma mochila.'

# Configuração da progressbar
progress-bar:
  amount: 10
  symbol: ':'
  color-yes: '&a'
  color-not: '&7'