#          ____ _               _   ____  _                 ____  _                       _             _       _     _
#  _   _ / ___| |__   ___  ___| |_/ ___|| |__   ___  _ __ |  _ \(_)_ __   __ _ _ __ ___ (_) ___ ___   / \   __| | __| | ___  _ __
# | | | | |   | '_ \ / _ \/ __| __\___ \| '_ \ / _ \| '_ \| | | | | '_ \ / _` | '_ ` _ \| |/ __/ _ \ / _ \ / _` |/ _` |/ _ \| '_ \
# | |_| | |___| | | |  __/\__ \ |_ ___) | | | | (_) | |_) | |_| | | | | | (_| | | | | | | | (_| (_) / ___ \ (_| | (_| | (_) | | | |
#  \__, |\____|_| |_|\___||___/\__|____/|_| |_|\___/| .__/|____/|_|_| |_|\__,_|_| |_| |_|_|\___\___/_/   \_\__,_|\__,_|\___/|_| |_|
#  |___/                                            |_|
#

maximum:
  # Máximo que o preço poderá subir
  # em porcentagem
  add: 100.0
  # Máximo que o preço poderá diminuir (cair)
  # em porcentagem
  remove: -90.0
  # Máximo que o preço poderá flutuar a cada operação de compra e venda
  # em porcentagem
  adjust: 5.0

# Tempo em segundos para normalizar o preço do shop aos poucos
# deixe 0 para não ter normalização sem novas transações
time-reduce: 60

# Atualizar a placa e o holograma na mudança de preços
# PODE CAUSAR LAG
update-sign: false