# Mundos que poderão vir recompensas
Mundos:
  - 'world'
  - 'mundo'

Usar blocos: true
Usar mobs: true
Msg ganhou: true

# Recompensas droparem mesmo com inventário cheio
Inv cheio: false

# Coloque as regiões do worldguard para não bugar fragmentos
Regioes blacklist:
  - 'spawn'

# Encantamento que poderá ser aplicado no item
# para somar % de chances para ganhar recompensas
Encantamento:
  # Ativar o encantamento
  Ativar: true
  # Nome do encantamento
  Nome: 'Sortudo'
  # Chance que irá somar para ganhar recompensas
  Chance: 5.0
  # Livro do encantamento
  Item:
    CustomSkull: false
    URL: ''
    ID: 403
    Data: 0
    Glow: false
    Name: '&eLivro de encantamento'
    Lore:
      - '&7Sortudo I'
      - ''
      - '&eClique em cima de uma espada ou picareta para encantá-la.'
  # Itens que poderá ser aplicado
  Itens:
    - 'DIAMOND_SWORD'
    - 'GOLD_SWORD'
    - 'IRON_SWORD'
    - 'STONE_SWORD'
    - 'WOOD_SWORD'
    - 'DIAMOND_PICKAXE'
    - 'IRON_PICKAXE'
    - 'GOLD_PICKAXE'
    - 'STONE_PICKAXE'
    - 'WOOD_PICKAXE'

Blocos:
  Reco1:
    ID: STONE #id do bloco quebrado
    Data: 0 #data do bloco quebrado
    Chance: 50.0
    Mensagem: '&aVocê ganhou 1 recompensa por quebrar este bloco.'
    Actionbar: '&eVocê encontrou uma recompensa!'
    Title: '&eRecompensa encontrada'
    Gives:
      - '[daritem] item1'
      - 'say {player} ganhou 1 item na recompensa'

# Novo formato de pacotes de recompensa
Configuracoes_de_Loot:
  Mina_Vip_Loot:
    Region: 'mina_vip_region'
    Mundo:
      - 'world'
    Blocos_Gatilho:
      STONE:
        Data: 0
        Chance_Global: 10.0
        Recompensas_Possiveis:
          - '80,item_comum'
          - '15,item_raro'
          - '5,item_lendario'

# Vinculos dinamicos feitos por comando
# /recompensas setregion [nome_da_regiao] [id_do_bloco_recompensa]
Mapeamento_Region_Loot: { }

Mobs:
  Reco1:
    Entidade: 'PIG'
    Chance: 50.0
    Mensagem: '&aVocê ganhou 1 recompensa por matar este mob.'
    Actionbar: '&eVocê encontrou uma recompensa!'
    Title: '&eRecompensa encontrada'
    Gives:
      - '[daritem] item1'
      - 'say {player} ganhou 1 item na recompensa'

Items:
  item1:
    CustomSkull: true
    URL: 'http://textures.minecraft.net/texture/c641682f43606c5c9ad26bc7ea8a30ee47547c9dfd3c6cda49e1c1a2816cf0ba'
    ID: 0
    Data: 0
    Glow: true
    Name: '&eRecompensa 1'
    Lore:
      - ''
      - '&7Isto é uma recompensa.'
      - ''
    Mensagem: '&aVocê encontrou uma recompensa!'
    Actionbar: '&eRecompensa encontrada'
    Title: '&eRecompensa encontrada'

  item_comum:
    CustomSkull: false
    URL: ''
    ID: 264
    Data: 0
    Glow: false
    Name: '&aMoeda Estelar'
    Lore:
      - '&7Uma moeda comum.'
    Mensagem: '&aVocê achou uma Moeda Estelar!'

  item_raro:
    CustomSkull: false
    URL: ''
    ID: 388
    Data: 0
    Glow: true
    Name: '&bFragmento Raro'
    Lore:
      - '&7Um fragmento raro.'
    Mensagem: '&bVocê achou um Fragmento Raro!'

  item_lendario:
    CustomSkull: false
    URL: ''
    ID: 399
    Data: 0
    Glow: true
    Name: '&6Reliquia Lendaria'
    Lore:
      - '&7Muito dificil de encontrar.'
    Mensagem: '&6Você achou uma Relíquia Lendária!'
