Database:
  Tipo: SQLITE #Tipos: MYSQL, SQLITE, MYSQL_FAST
  IP: localhost:3306
  DB: test
  User: admin
  Pass: ''
  Debug: true

# Comandos e aliases do plugin
Comando:
  Comando: 'boss'
  Aliases: [ bosses ]

# Permitir colocar bosses e matar bosses apenas nos plots
Somente plot: false

# Verifica se há mobs por perto antes de spawnar
# Raio em blocos.
Raio checagem: 5

# Deixar a matadora inquebrável
Matadora inquebravel: true

# Dar as recompensas diretamente ao jogador (sem armazenar)
RecompensasDiretas: false

# Spawnar os bosses em uma área definida
SpawnLocation: false

# Mundos bloqueados para colocar bosses
MundosBloqueados:
  - 'none'

# Delay para hitar os bosses
# Deixe 0 para não usar
# em millisegundos
# evite dupes com isso
Hit-delay: 500

# Configurações dos efeitos
Efeitos:
  Explosao:
    # Lista da 1.8: https://helpch.at/docs/1.8/org/bukkit/Sound.html
    # Lista da 1.16: https://helpch.at/docs/1.16.2/org/bukkit/Sound.html
    # Lista da 1.18: https://helpch.at/docs/1.18/org/bukkit/Sound.html
    Som: 'EXPLODE'
    # Lista da 1.8: https://helpch.at/docs/1.8/org/bukkit/Effect.html
    # Lista da 1.16: https://helpch.at/docs/1.16.2/org/bukkit/Effect.html
    # Lista da 1.18: https://helpch.at/docs/1.18/org/bukkit/Effect.html
    Particula1: 'LAVA'
    Particula2: 'VILLAGER_ANGRY'
    Particula3: 'CLOUD'
  # Lista da 1.8: https://helpch.at/docs/1.8/org/bukkit/potion/PotionEffectType.html
  # Lista da 1.16: https://helpch.at/docs/1.16.2/org/bukkit/potion/PotionEffectType.html
  # Lista da 1.18: https://helpch.at/docs/1.18/org/bukkit/potion/PotionEffectType.html
  Veneno: 'POISON'
  Nausea: 'CONFUSION'
  Cegueira: 'BLINDNESS'

# Mensagens gerais do plugin
Mensagens:
  Permissao: '&cVocê não tem permissão para isto.'
  Nao encontrado: '&cJogador não encontrado.'
  Nao e numero: '&cO argumento não é um número.'
  Inv cheio: '&cSeu inventário está cheio.'
  Usar matadora: '&cVocê deve usar uma matadora para bater neste boss.'
  Permissao plot: '&cVocê não tem permissão neste terreno.'
  Mobs spawners: '&cHá mobs ou spawners num raio de 5 blocos.'
  Nao tem money: '&cVocê não possui a quantia necessária de money: &7{money}&c.'
  Comprou matadora: '&aVocê adquiriu uma matadora {matadora}&a com sucesso.'
  Comprou boss: '&aVocê adquiriu um boss {boss}&a com sucesso.'
  Deu boss: '&aVocê deu &7{quantia}x {boss}&a para o jogador &7{player}&a.'
  Recebeu boss: '&aVocê recebeu &7{quantia}x {boss}&a.'
  Deu matadora: '&aVocê deu &71 {matadora}&a para o jogador &7{player}&a.'
  Recebeu matadora: '&aVocê recebeu &71 {matadora}&a.'
  Pos1: '&aVocê definiu a POS-1 da arena boss.'
  Pos2: '&aVocê definiu a POS-2 da arena boss.'
  Spawned: |
    <nl>
    &a&lBOSS! &aO jogador &f{player}&a spawnou um &r{boss}&a. &aVá até ele na &7/warp bosses &8(X:{x}, Y:{y}, Z:{z} -> {world})
    <nl>
  AdicionadoFiltro: '&aEste item foi adicionado ao filtro.'
  RemovidoFiltro: '&aEste item foi removido do filtro.'

# Configuração da barra de progresso
Progress bar:
  Quantia: 10
  Simbolo: ':'
  Cor sim: '&a'
  Cor nao: '&7'

# Sistema de lores
lore:
  filter-remove: ['&cClique para remover do filtro']

# Setas dos menus.
Setas:
  Voltar:
    CustomSkull: false
    URL: ''
    ID: 262
    Data: 0
    Glow: true
    Name: '&cVoltar'
    Lore:
      - '&7Clique para voltar ao menu anterior.'
  Anterior:
    CustomSkull: false
    URL: ''
    ID: 262
    Data: 0
    Glow: true
    Name: '&cAnterior'
    Lore:
      - '&7Clique para ir à página anterior.'
  Proximo:
    CustomSkull: false
    URL: ''
    ID: 262
    Data: 0
    Glow: true
    Name: '&aPróximo'
    Lore:
      - '&7Clique para ir à próxima página.'

# Formatos de quantia e money
Formats:
  - ''
  - ''
  - 'K'
  - 'M'
  - 'B'
  - 'T'
  - 'Q'
  - 'QQ'
  - 'S'
  - 'SS'
  - 'O'
  - 'N'
  - 'D'