#         _____
#  _   _| ____|___ ___  _ __   ___  _ __ ___  _   _
# | | | |  _| / __/ _ \| '_ \ / _ \| '_ ` _ \| | | |
# | |_| | |__| (_| (_) | | | | (_) | | | | | | |_| |
#  \__, |_____\___\___/|_| |_|\___/|_| |_| |_|\__, |
#  |___/                                      |___/
#
# Discord: discord.ystoreplugins.com.br
# Site: ystoreplugins.com.br
#

# Modo de depuração para correção de problemas no plugin.
debug-mode: false

#      ___      _        _
#     /   \__ _| |_ __ _| |__   __ _ ___  ___
#    / /\ / _` | __/ _` | '_ \ / _` / __|/ _ \
#   / /_// (_| | || (_| | |_) | (_| \__ \  __/
#  /___,' \__,_|\__\__,_|_.__/ \__,_|___/\___|
#
# Configurações do banco de dados.

database:
  # Determina o tipo de banco de dados. Valores válidos: [SQLITE, MYSQL, HIKARI (recomendado)]
  storage-type: SQLITE

  # Dados para conexão ao banco de dados MYSQL.
  data:
    # Endereço de conexão do banco de dados. [EX: 127.0.0.1]
    host: localhost
    # Porta de conexão do banco de dados. [EX: 3306]
    port: 3306
    # Nome do banco de dados a ser conectado. [EX: minecraft]
    database: ''
    # Usuário de conexão. [EX: root]
    username: ''
    # Senha do usuário de conexão: [EX: 123]
    password: ''
    # Prefixo para diferenciar no redis
    prefix: ''

# Configurações do servidor redis
redis:
  # Ativar a conexão com o redis
  enabled: false
  # Endereço de conexão. [EX: 127.0.0.1]
  host: 'localhost'
  # Porta de conexão. [EX: 3306]
  port: 6379
  # Usuário de conexão. [EX: root]
  username: ''
  # Senha do usuário de conexão: [EX: 123]
  password: ''

#   __      _   _   _
#  / _\ ___| |_| |_(_)_ __   __ _ ___
#  \ \ / _ \ __| __| | '_ \ / _` / __|
#  _\ \  __/ |_| |_| | | | | (_| \__ \
#  \__/\___|\__|\__|_|_| |_|\__, |___/
#
# Sistemas principais.

# Sistemas gerais
general:
  # Ativar transações com players não conectados
  offline-transactions: true
  # Ao digitar /money abrir o menu.
  # False = Vai enviar a quantia de money que ele tem no chat
  # True = Vai abrir o menu
  money-menu: true
  # Ao ativar irá abrir o menu do top ao digitar /money top
  top-menu: true
  # Tempo que irá atualizar o top
  # Em segundos
  top-delay: 600
  # Tag do magnata no chat
  top-tag: '&2[$]'

# Preferências obrigatórias do sistema de coins
coin-preferences:
  # Quantia de money que o jogador vai começar
  initial-amount: 30.0
  # Formato do money na quantia singular
  singular-format: 'coin'
  # Formato do money no plural
  plural-format: 'coins'

# Configuração do money top em chat
top-chat:
  # O plugin irá reconhecer quando isto for apenas espaços e vai removê-los.
  rich-format: '{magnata} '
  # O plugin irá reconhecer quando isto for apenas espaços e vai removê-los.
  prefix-format: '%luckperms_prefix% '
  # Tags juntas
  tags: '{magnata}{prefixo}'
  # Formato geral do jogador no top
  player-format: '  &f{pos}º {tags}&7{player}&2: &7($ {money})'
  # Mensagem do TOP
  message: |
    &r
    &2Top 10 Mais Ricos &7(Atualizado de 10 em 10 minutos)
    &r
    {formato}
    &r

# Sistema de cheques do plugin
checks:
  main-check:
    material: PAPER
    glow: true
    name: '&aCheque de dinheiro'
    lore:
      - ''
      - '&7Criado por: &a{player}&7.'
      - '&7Criado em: &f{data} &8- &f{hora}&7.'
      - ''
      - '&bValor do cheque: &a{money}&b.'
      - ''
      - '&7Clique com botão direito para ativar'
  media-check:
    material: PAPER
    glow: true
    name: '&aCheque de dinheiro'
    lore:
      - ''
      - '&bValor do cheque: &a{amount}&b.'
      - ''
      - '&7Clique com botão direito para ativar'
  death-check:
    enabled: true
    # Máximo de money para o morto perder ( x % do seu money )
    maximum: 20000.0
    # Quando o jogador morrer, perder esta % de money
    percentage: 10.0
    item:
      material: PAPER
      glow: true
      name: '&aCheque de dinheiro'
      lore:
        - ''
        - '&7Dropado por: &a{player}&7.'
        - '&7Aniquiliado em: &f{data} &8- &f{hora}&7.'
        - ''
        - '&bValor do cheque: &a{money}&b.'
        - ''
        - '&7Clique com botão direito para ativar'

# Configurações do Holograma do NPC
npc:
  # Altura do holograma em cima do NPC
  offset: 3.1
  # Holograma do NPC
  hologram-lines:
    - '&a&lTOP &7&l#{pos}'
    - ''
    - '&e{nome}'
    - '&7Money: &f{money}'
    - ''