#        __  __            _        _
#  _   _|  \/  | __ _ _ __| | _____| |_
# | | | | |\/| |/ _` | '__| |/ / _ \ __|
# | |_| | |  | | (_| | |  |   <  __/ |_
#  \__, |_|  |_|\__,_|_|  |_|\_\___|\__|
#  |___/
#
# Modo de depuração para correção de problemas no plugin.
debug-mode: false

#      ___      _        _
#     /   \__ _| |_ __ _| |__   __ _ ___  ___
#    / /\ / _` | __/ _` | '_ \ / _` / __|/ _ \
#   / /_// (_| | || (_| | |_) | (_| \__ \  __/
#  /___,' \__,_|\__\__,_|_.__/ \__,_|___/\___|
#
# Configurações do banco de dados.

database:
  # Determina o tipo de banco de dados. Valores válidos: [SQLITE, MYSQL, HIKARI (recomendado)]
  storage-type: SQLITE

  # Dados para conexão ao banco de dados MYSQL.
  data:
    # Endereço de conexão do banco de dados. [EX: 127.0.0.1]
    host: localhost
    # Porta de conexão do banco de dados. [EX: 3306]
    port: 3306
    # Nome do banco de dados a ser conectado. [EX: minecraft]
    database: ''
    # Usuário de conexão. [EX: root]
    username: ''
    # Senha do usuário de conexão: [EX: 123]
    password: ''

# Delay para carregar os dados depois do login
# Necessário para usar em servidor de mina separado
# Recomendado: 20 ticks
login-delay: 20

# Ativar a troca do sistema de chat quando estiver no mohist
# compatível apenas com: UltimateChat, nChat e Legendchat
mohist-chat: false

# Sistemas gerais do plugin
general:
  # Tempo padrão para começar a venda
  default-time: 1800
  # Quantia máxima de vendas simultâneas que o servidor pode ter
  # deixe 0 para ser infinito
  max-sells: 0
  # Quantia máxima de vendas simultâneas que o jogador pode fazer
  # deixe 0 para ser infinito
  player-max-sells: 1
  # Quantia máxima de vendas destacadas que o jogador pode fazer
  # deixe 0 para ser infinito
  player-max-sponsored: 1
  # Tempo mínimo para iniciar uma venda
  # em segundos
  min-time: 900
  # Tempo máximo para iniciar uma venda
  # em segundos
  max-time: 21600
  # Custos para destacar o anúncio
  sponsor-prices:
    price1:
      provider: 'money'
      amount: 100.0

# Sistema de blacklist
black-list:
  # Materiais que estarão na black-list
  materials: [ 'STONE', 'LOG:0' ]
  # NBTTags que estarão na black-list
  nbt-tags: []

# Sistema de npc
npc:
  skin: 'Pitombaa'
  hologram:
    offset: 3.4
    hologram:
      - '&6&lMERCADO'
      - '&7Faça o comércio rápido dos itens!'
      - '[item]EMERALD'