Comando:
  Comando: 'fragmentos'
  Aliases: []

# Tipo de formatos de quantia disponíveis: LETRA (K,M,B,T...) e NUMERO (100,00)
Formatacao: 'LETRA'

# Ativar o sistema de loja
Loja ativar: true

# Abrir a loja ao clicar com botão direito no fragmento
Loja interagir: true

# Dropar os fragmentos no chão ao conseguí-los
Dropar: false

# Habilitar a compra com o botão esquerdo
CompraEsquerdo: true

# Habilitar a compra com o botão direito
CompraDireito: true

# Habilitar o drop de fragmentos em bosses
Bosses: false

# Mensagens gerais do plugin
Mensagens:
  Permissao: '&cVocê não tem permissão para fazer isto.'
  Nao encontrado: '&cJogador não encontrado'
  Nao e numero: '&cO argumento não é um número.'
  Deu: '&aVocê deu &ex{quantia} &afragmento&e {fragmento}&a para o jogador &e{player}'
  Inv cheio: '&cVocê está com o inventário cheio.'
  Suficiente: '&cVocê não possui fragmentos suficiente.'
  Comprou: '&aVocê adquiriu coisas na loja de fragmentos.'
  Recebeu: '&aVocê recebeu &7{quantia} &ade fragmentos.' #deixe '' para não usar
  Money: '&cVocê não possui &f{money} &ccoins.'

# Blacklist de mundos
World blacklist:
  - 'nenhum'

# Coloque as regiões que o plugin vai funcionar
Whitelist:
  Ativar: false
  Lista:
    - 'mina'

Voltar:
  CustomSkull: false #se colocar true, coloque o URL
  URL: ''
  ID: 262
  Data: 0
  Glow: false
  Name: '&cVoltar'
  Lore:
    - ''
    - '&eClique para voltar.'
    - ''

Loja:
  Tamanho: 27
  Nome: '&aCategorias da loja'

# Tipos: MATAR, QUEBRAR, MCMMO (upar nível)
Fragmentos:
  Fragmento1:
    Metodos:
      Metodo1:
        Tipo: 'MATAR'
        Ativar especifico: false
        Especifico:
          - 'none'
        Chance: 50.0
        Quantia: 1
      Metodo2:
        Tipo: 'QUEBRAR'
        Ativar especifico: true
        Especifico:
          - 'STONE'
        Chance: 50.0
        Quantia: 1
      Metodo3:
        Tipo: 'MATAR'
        Ativar especifico: true
        Especifico:
          - 'PLAYER'
        Chance: 20.0
        Quantia: 1
    Mensagens:
      Chat:
        Ativar: true
        Mensagem: '&aVocê encontrou &e{quantia} &afragmentos de rocha.'
      Actionbar:
        Ativar: true
        Mensagem: '&aVocê encontrou &e{quantia} &afragmentos de rocha.'
      Title:
        Ativar: true
        Title: '&aVocê encontrou &e{quantia} &afragmentos de rocha.'
    Item:
      CustomSkull: true
      URL: 'http://textures.minecraft.net/texture/36d1fabdf3e342671bd9f95f687fe263f439ddc2f1c9ea8ff15b13f1e7e48b9'
      ID: 0
      Data: 0
      Glow: false
      Name: '&aFragmento de Rocha'
      Lore:
        - ''
        - '&eUse este fragmento na loja: /fragmentos'
        - ''
  Fragmento2:
    Metodos:
      Metodo1:
        Tipo: 'MATAR'
        Ativar especifico: false
        Especifico:
          - 'none'
        Chance: 20.0
        Quantia: 1
      Metodo2:
        Tipo: 'QUEBRAR'
        Ativar especifico: true
        Especifico:
          - 'STONE'
        Chance: 20.0
        Quantia: 1
      Metodo3:
        Tipo: 'MATAR'
        Ativar especifico: true
        Especifico:
          - 'PLAYER'
        Chance: 50.0
        Quantia: 1
    Mensagens:
      Chat:
        Ativar: true
        Mensagem: '&aVocê encontrou &e{quantia} &afragmentos de terra.'
      Actionbar:
        Ativar: true
        Mensagem: '&aVocê encontrou &e{quantia} &afragmentos de terra.'
      Title:
        Ativar: true
        Title: '&aVocê encontrou &e{quantia} &afragmentos de terra.'
    Item:
      CustomSkull: true
      URL: 'http://textures.minecraft.net/texture/6036bf97926c02a6da524bf487db5b9742d5bc5884aa2faf94e576fc869'
      ID: 0
      Data: 0
      Glow: false
      Name: '&aFragmento de Terra'
      Lore:
        - ''
        - '&eUse este fragmento na loja: /fragmentos'
        - ''

Formats:
  - ''
  - ''
  - 'K'
  - 'M'
  - 'B'
  - 'T'
  - 'Q'
  - 'QQ'
  - 'S'
  - 'SS'
  - 'O'
  - 'N'