#         __  __ _                    _    _____ _  __
#  _   _|  \/  (_)_ __   __ _ ___   / \  |  ___| |/ /
# | | | | |\/| | | '_ \ / _` / __| / _ \ | |_  | ' /
# | |_| | |  | | | | | | (_| \__ \/ ___ \|  _| | . \
#  \__, |_|  |_|_|_| |_|\__,_|___/_/   \_\_|   |_|\_\
#  |___/
#
# Discord: discord.ystoreplugins.com.br
# Site: ystoreplugins.com.br
#

# Modo de depuração para correção de problemas no plugin.
debug-mode: false

#      ___      _        _
#     /   \__ _| |_ __ _| |__   __ _ ___  ___
#    / /\ / _` | __/ _` | '_ \ / _` / __|/ _ \
#   / /_// (_| | || (_| | |_) | (_| \__ \  __/
#  /___,' \__,_|\__\__,_|_.__/ \__,_|___/\___|
#
# Configurações do banco de dados.

database:
  # Determina o tipo de banco de dados. Valores válidos: [SQLITE, MYSQL, HIKARI (recomendado)]
  storage-type: SQLITE

  # Dados para conexão ao banco de dados MYSQL.
  data:
    # Endereço de conexão do banco de dados. [EX: 127.0.0.1]
    host: localhost
    # Porta de conexão do banco de dados. [EX: 3306]
    port: 3306
    # Nome do banco de dados a ser conectado. [EX: minecraft]
    database: ''
    # Usuário de conexão. [EX: root]
    username: ''
    # Senha do usuário de conexão: [EX: 123]
    password: ''

#   __      _   _   _
#  / _\ ___| |_| |_(_)_ __   __ _ ___
#  \ \ / _ \ __| __| | '_ \ / _` / __|
#  _\ \  __/ |_| |_| | | | | (_| \__ \
#  \__/\___|\__|\__|_|_| |_|\__, |___/
#
# Sistemas principais.

# Delay para carregar os dados depois do login
# Necessário para usar em servidor de mina separado
# Recomendado: 20 ticks
login-delay: 20

# Delay para carregar os dados depois do servidor ligar
# Necessário para as crates em bloco
# Recomendado: 20 ticks
load-delay: 20

# Este limite serve para recolher recompensas
# Desativar ou aumentar o limite pode gerar lag
# e em alguns casos crashar o servidor.
limit:
  enabled: true
  # Máximo que irá recolher por vez
  max: 1000

# Opções gerais
general:
  # Abrir o menu ao digitar apenas /minaafk
  command-menu: false
  # Acumular os bonus
  accumulate-bonus: false
  # Deletar a recompensa ao clicar com botão direito
  right-delete-reward: true

# Formatador de mensagens
format:
  bonus-has: '&a+{bonus}% por ser {display}&a.'
  bonus-no-has: ''

# Mensagens gerais
messages:
  stopped:
    title: '&3MINA AFK<nl>&fParou de minerar.'
    actionbar: ''
    chat: ''
  wait:
    title: ''
    actionbar: '&cAguarde {time}.'
    chat: ''

 # Varinha de seleção da área da mina
wand:
  material: GOLD_AXE
  name: '&eSelecionar região'
  glow: true
  lore: [ '&aBotão esquerdo para selecionar a POS1', '&aBotão direito para selecionar a POS2']