#       _____              _
#  _   |_   _| __ __ _  __| | ___  ___
# | | | || || '__/ _` |/ _` |/ _ \/ __|
# | |_| || || | | (_| | (_| |  __/\__ \
#  \__, ||_||_|  \__,_|\__,_|\___||___/
#  |___/
# Discord: discord.ystoreplugins.com.br
# Site: ystoreplugins.com.br
#

# Sistemas gerais
general:
  # Ativar enviar pedido de troca ao interagir com um jogador
  # (clicar com o botão direito nele)
  interact-trade: true
  # Distância máxima entre blocos que irá permitir a troca entre jogadores
  # deixe 0 para não usar
  max-distance: 0

# Sistema de blacklist
black-list:
  # Materiais que estarão na black-list
  materials: [ 'STONE', 'LOG:0' ]
  # NBTTags que estarão na black-list
  nbt-tags: []

# Sistema de whitelist
white-list:
  # Ativar a whitelist
  enabled: false
  # Materiais que estarão na white-list
  materials: [ 'LOG:1', 'TRIPWIRE_HOOK' ]