#          ____                     ____  _                 _
#  _   _|  _ \ ___  ___  ___ __ _/ ___|(_)_ __ ___  _ __ | | ___  ___
# | | | | |_) / _ \/ __|/ __/ _` \___ \| | '_ ` _ \| '_ \| |/ _ \/ __|
# | |_| |  __/  __/\__ \ (_| (_| |___) | | | | | | | |_) | |  __/\__ \
#  \__, |_|   \___||___/\___\__,_|____/|_|_| |_| |_| .__/|_|\___||___/
#  |___/                                           |_|
#
# Discord: discord.ystoreplugins.com.br
# Site: ystoreplugins.com.br
#

# Modo de depuração para correção de problemas no plugin.
debug-mode: false

#      ___      _        _
#     /   \__ _| |_ __ _| |__   __ _ ___  ___
#    / /\ / _` | __/ _` | '_ \ / _` / __|/ _ \
#   / /_// (_| | || (_| | |_) | (_| \__ \  __/
#  /___,' \__,_|\__\__,_|_.__/ \__,_|___/\___|
#
# Configurações do banco de dados.

database:
  # Determina o tipo de banco de dados. Valores válidos: [SQLITE, MYSQL, HIKARI (recomendado)]
  storage-type: SQLITE

  # Dados para conexão ao banco de dados MYSQL.
  data:
    # Endereço de conexão do banco de dados. [EX: 127.0.0.1]
    host: localhost
    # Porta de conexão do banco de dados. [EX: 3306]
    port: 3306
    # Nome do banco de dados a ser conectado. [EX: minecraft]
    database: ''
    # Usuário de conexão. [EX: root]
    username: ''
    # Senha do usuário de conexão: [EX: 123]
    password: ''

#   __      _   _   _
#  / _\ ___| |_| |_(_)_ __   __ _ ___
#  \ \ / _ \ __| __| | '_ \ / _` / __|
#  _\ \  __/ |_| |_| | | | | (_| \__ \
#  \__/\___|\__|\__|_|_| |_|\__, |___/
#
# Sistemas principais.

# Delay para carregar os dados depois do login
# Necessário para usar em servidor de mina separado
# Recomendado: 20 ticks
login-delay: 20

# Este limite serve para recolher recompensas
# Desativar ou aumentar o limite pode gerar lag
# e em alguns casos crashar o servidor.
limit:
  enabled: true
  # Máximo que irá recolher por vez
  max: 1000

# Sistemas gerais
general:
  # Deletar a recompensa ao clicar com botão direito
  right-delete-reward: true
  # Delay para teleportar novamente para o local da pesca
  # em segundos
  location-delay: 10
  # Delay para comprar novamente uma vara de pesca
  # em segundos
  buy-delay: 10
  # Tempo para recompensar o jogador (em segundos)
  fish-time: 10
  # Nome da skill de pesca no mcmmo
  mcmmo-skill: 'FISHING'
  # Permissão para pescar
  # Deixe vazio para não usar
  permission: ''
  # Raio de checagem de click na água
  radius: 10
  # Mundos onde a pesca é permitida
  whitelist-world: [ 'world', 'PlotWorld' ]

# Configuração da barra de progresso
progress-bar:
  amount: 10
  symbol: ':'
  color-yes: '&a'
  color-no: '&7'

# Sistema de npc
npc:
  skin: 'Pitombaa'
  hologram:
    offset: 3.4
    hologram:
      - '&6&lPESCA'
      - '&7Pesque recompensas no servidor!'
      - '[item]EMERALD'

# Sistema de boosters
boosters:
  booster1:
    # Item do booster
    item:
      material: 'EXP_BOTTLE'
      name: '&aBooster de Pesca'
      lore:
        - '&7Tenha mais chances de receber'
        - '&7melhores recompensas.'
        - ''
        - '&f> Bonus: &a10%&f.'
        - '&f> Duração: &b60s&f.'
        - ''
    # Duração desse booster
    # em segundos
    time: 60
    # Bonus de chance a mais
    bonus: 10.0
    # Bonus de xp a mais para a vara
    bonus-xp: 10.0