# Opções gerais do plugin
Opcoes:
  # Permitir colocar mochila dentro de mochila
  Mochila dentro: true
  # Ativar o uso de shift na mochila
  Shift: false
  # Ativar o uso de teclas numéricas na mochila
  Numkeys: false
  # Abrir a mochila com botão esquerdo
  AbrirEsquerdo: true
  # Abrir a mochila com botão direito
  AbrirDireito: true
  # Blacklist de itens que não poderão ser colocados na mochila
  Item blacklist:
    - 'MOB_SPAWNER'
  # Som ao abrir a mochila
  Som: ''