#          ____                _     _
#  _   _ / ___|__ _ _ __ ___ | |__ (_) ___
# | | | | |   / _` | '_ ` _ \| '_ \| |/ _ \
# | |_| | |__| (_| | | | | | | |_) | | (_) |
#  \__, |\____\__,_|_| |_| |_|_.__/|_|\___/
#  |___/
# Discord: discord.ystoreplugins.com.br
# Site: ystoreplugins.com.br
#

#   __      _   _   _
#  / _\ ___| |_| |_(_)_ __   __ _ ___
#  \ \ / _ \ __| __| | '_ \ / _` / __|
#  _\ \  __/ |_| |_| | | | | (_| \__ \
#  \__/\___|\__|\__|_|_| |_|\__, |___/
#
# Sistemas principais.

# Delay para carregar os dados depois do login
# Necessário para usar em servidor de mina separado
# Recomendado: 20 ticks
login-delay: 20

# Sistema de npc
npc:
  skin: 'Pitombaa'
  hologram:
    offset: 3.4
    hologram:
      - '&6&lCâmbio'
      - '&7Clique para trocar suas economias.'
      - '[item]EMERALD'