#          ____
#  _   _ / ___|__ _ _ __ ___  _ __   ___
# | | | | |   / _` | '_ ` _ \| '_ \ / _ \
# | |_| | |__| (_| | | | | | | |_) | (_) |
#  \__, |\____\__,_|_| |_| |_| .__/ \___/
#  |___/                     |_|
#
# Discord: discord.ystoreplugins.com.br
# Site: ystoreplugins.com.br
#

# Modo de depuração para correção de problemas no plugin.
debug-mode: false

#      ___      _        _
#     /   \__ _| |_ __ _| |__   __ _ ___  ___
#    / /\ / _` | __/ _` | '_ \ / _` / __|/ _ \
#   / /_// (_| | || (_| | |_) | (_| \__ \  __/
#  /___,' \__,_|\__\__,_|_.__/ \__,_|___/\___|
#
# Configurações do banco de dados.

database:
  # Determina o tipo de banco de dados. Valores válidos: [SQLITE, MYSQL, HIKARI (recomendado)]
  storage-type: SQLITE

  # Dados para conexão ao banco de dados MYSQL.
  data:
    # Endereço de conexão do banco de dados. [EX: 127.0.0.1]
    host: localhost
    # Porta de conexão do banco de dados. [EX: 3306]
    port: 3306
    # Nome do banco de dados a ser conectado. [EX: minecraft]
    database: ''
    # Usuário de conexão. [EX: root]
    username: ''
    # Senha do usuário de conexão: [EX: 123]
    password: ''

#   __      _   _   _
#  / _\ ___| |_| |_(_)_ __   __ _ ___
#  \ \ / _ \ __| __| | '_ \ / _` / __|
#  _\ \  __/ |_| |_| | | | | (_| \__ \
#  \__/\___|\__|\__|_|_| |_|\__, |___/
#
# Sistemas principais.

general:
  # Permitir entrar neste servidor mesmo banido
  # Necessário estar ativado para o sistema de redirect funcionar
  lobby-mode: false
  # Ative apenas se estiver usando o waterfall
  waterfall-kick: true
  # Permitir de conversar em chat custom quando estiver mutado
  # Chat custom = Legendchat, nChat...
  mute-custom-chat-enabled: false
  # Permitir de conversar em chat do minecraft
  # Chat do minecraft = Quando não tem plugin de chat
  mute-minecraft-chat-enabled: false
  # Permitir de usar comandos quando estiver mutado
  mute-commands-enabled: true
  # Whitelist de comandos permitidos para usar quando estiver mutado
  mute-commands-whitelist: []
  # Tempo para atualizar o report de punições
  # Em segundos
  report-time: 1800

proxy:
  # Nome deste servidor na config do proxy
  server-name: 'lobby'
  # Lista de servidores no proxy
  server-list:
    - 'lobby'
    - 'mina'

redirect:
  enabled: false
  # Tipos disponíveis
  # SERVER (envia para outro servidor)
  # LOCATION (envia para um local definido no próprio lobby)
  type: 'SERVER'
  # Servidor que irá redirecionar o jogador caso esteja banido
  # (legal para fazer uma área de jaula)
  server: 'mina'

discord:
  # exclusivo yDiscordHook
  # enviar o embed no privado
  discordhook:
    enabled: true
    dm-tempmute-embed: 'tempmute'
    dm-mute-embed: 'mute'
    dm-ban-embed: 'ban'
    dm-banip-embed: 'banip'
    dm-tempban-embed: 'tempban'
    dm-unban-embed: 'unban'
    dm-unmute-embed: 'unmute'
    dm-kick-embed: 'kick'
    dm-warn-embed: 'warn'
  # enviar o embed em um chat
  webhook:
    enabled: true
    chat-tempmute-embed: 'tempmute'
    chat-mute-embed: 'mute'
    chat-ban-embed: 'ban'
    chat-banip-embed: 'banip'
    chat-tempban-embed: 'tempban'
    chat-unban-embed: 'unban'
    chat-unmute-embed: 'unmute'
    chat-kick-embed: 'kick'
    chat-warn-embed: 'warn'