#          ____ _                 ____          _ _        _       _     _
#  _   _ / ___| | __ _ _ __  ___|  _ \ ___  __| (_)___   / \   __| | __| | ___  _ __
# | | | | |   | |/ _` | '_ \/ __| |_) / _ \/ _` | / __| / _ \ / _` |/ _` |/ _ \| '_ \
# | |_| | |___| | (_| | | | \__ \  _ <  __/ (_| | \__ \/ ___ \ (_| | (_| | (_) | | | |
#  \__, |\____|_|\__,_|_| |_|___/_| \_\___|\__,_|_|___/_/   \_\__,_|\__,_|\___/|_| |_|
#  |___/
#
# Discord: discord.ystoreplugins.com.br
# Site: ystoreplugins.com.br
#

# Configurações do servidor redis
redis:
  # Ativar a conexão com o redis
  enabled: false
  # Endereço de conexão. [EX: 127.0.0.1]
  host: 'localhost'
  # Porta de conexão. [EX: 3306]
  port: 6379
  # Usuário de conexão. [EX: root]
  username: ''
  # Senha do usuário de conexão: [EX: 123]
  password: ''