#         _____    _
#  _   _|  ___|__(_)_ __ __ _ ___
# | | | | |_ / _ \ | '__/ _` / __|
# | |_| |  _|  __/ | | | (_| \__ \
#  \__, |_|  \___|_|_|  \__,_|___/
#  |___/
#
# Modo de depuração para correção de problemas no plugin.
debug-mode: false

#      ___      _        _
#     /   \__ _| |_ __ _| |__   __ _ ___  ___
#    / /\ / _` | __/ _` | '_ \ / _` / __|/ _ \
#   / /_// (_| | || (_| | |_) | (_| \__ \  __/
#  /___,' \__,_|\__\__,_|_.__/ \__,_|___/\___|
#
# Configurações do banco de dados.

database:
  # Determina o tipo de banco de dados. Valores válidos: [SQLITE, MYSQL, HIKARI (recomendado)]
  storage-type: SQLITE

  # Dados para conexão ao banco de dados MYSQL.
  data:
    # Endereço de conexão do banco de dados. [EX: 127.0.0.1]
    host: localhost
    # Porta de conexão do banco de dados. [EX: 3306]
    port: 3306
    # Nome do banco de dados a ser conectado. [EX: minecraft]
    database: ''
    # Usuário de conexão. [EX: root]
    username: ''
    # Senha do usuário de conexão: [EX: 123]
    password: ''

# Sistemas gerais
general:
  # Porcentagem atual referente ao tempo total que irá permitir renovar o aluguel
  renew-percent: 10.0
  # Quantia máxima de feiras que um jogador pode ter
  feira-max: 2
  hologram-lines:
    rent:
      - '[item]{icon}'
      - '&fFeira {feira}'
      - '&fDono: &a{owner}'
      - '&fO aluguel vence em: &a{expire}'
    available:
      - '[item]{icon}'
      - '&fFeira {feira}'
      - '&7Renovação a cada: &f{time_to_renew}'
      - '&aFeira disponível para alugar!'

# Configuração do item da varinha
wand:
  material: 'GOLD_AXE'
  name: '&eSeleção de Área'
  lore: [ '&fFeira: &f{feira}', '', '&aEsquerdo -> POS1', '&aDireito -> POS2' ]