#        _____ _                     _
#  _   _|  ___| | ___  _ __ ___  ___| |_ __ _
# | | | | |_  | |/ _ \| '__/ _ \/ __| __/ _` |
# | |_| |  _| | | (_) | | |  __/\__ \ || (_| |
#  \__, |_|   |_|\___/|_|  \___||___/\__\__,_|
#  |___/
#
# Modo de depuração para correção de problemas no plugin.
debug-mode: false

#      ___      _        _
#     /   \__ _| |_ __ _| |__   __ _ ___  ___
#    / /\ / _` | __/ _` | '_ \ / _` / __|/ _ \
#   / /_// (_| | || (_| | |_) | (_| \__ \  __/
#  /___,' \__,_|\__\__,_|_.__/ \__,_|___/\___|
#
# Configurações do banco de dados.

database:
  # Determina o tipo de banco de dados. Valores válidos: [SQLITE, MYSQL, HIKARI (recomendado)]
  storage-type: SQLITE

  # Dados para conexão ao banco de dados MYSQL.
  data:
    # Endereço de conexão do banco de dados. [EX: 127.0.0.1]
    host: localhost
    # Porta de conexão do banco de dados. [EX: 3306]
    port: 3306
    # Nome do banco de dados a ser conectado. [EX: minecraft]
    database: ''
    # Usuário de conexão. [EX: root]
    username: ''
    # Senha do usuário de conexão: [EX: 123]
    password: ''

# Delay para carregar os dados depois do login
# Necessário para usar em servidor de mina separado
# Recomendado: 20 ticks
login-delay: 20

# Este limite serve para recolher recompensas
# Desativar ou aumentar o limite pode gerar lag
# e em alguns casos crashar o servidor.
limit:
  enabled: true
  # Máximo que irá recolher por vez
  max: 1000

# Altura do void do seu servidor
void-detect: 0

# Coloque o identificador da sua skill do mcMMO ou AuraSkills
skill-identify: 'MINING'

general:
  # Acumular os bônus que tiver permissão
  accumulate-bonus: false
  formatter-bonus-has: '&a+{bonus}% por ser {display}&a.'
  formatter-bonus-no-has: ''
  # Ativar a invisibilidade na área da floresta
  invisibility: false
  # Esconder o encantamento na lore da ferramenta caso o player desative ele
  # caso esteja false, o encantamento ficará riscado na lore da ferramenta
  hide-deactivated: false
  # Fazer com que a ferramenta nunca quebre
  tool-unbreakable: true
  # Permitir a troca de itens via numkeys
  numkeys: false
  # Habilitar o menu de evolução ao interagir com a ferramenta sem shift
  no-shfit-evolution: true
  # Habilitar o menu de evolução ao interagir com a ferramenta com shift
  shfit-evolution: true
  # Para evoluir as classes ele deverá seguir a ordem delas?
  classes-order: true
  # Evoluir a picareta com a ação do botão direito
  evolute-right: true
  # Evoluir a picareta com a ação do botão Q
  evolute-q: true
  # Máximo permitido para evoluir com Q
  evolute-q-max: 0
  # Skin default da picareta
  skin-default: ''
  # Necessitar estar com o inv vazio
  inv-empty: false
  # Materiais que irão ser reconhecidos na skin
  skin-materiais:
    - 'WOOD'
    - 'STONE'
    - 'IRON'
    - 'GOLD'
    - 'DIAMOND'
  # Lista de comandos permitidos na floresta
  commands-allowed:
    - '/g'
    - '/l'
    - '/floresta'
    - '/florestas'
  # Lista de comandos para sair da floresta
  commands-exit:
    - '/sair'
    - '/spawn'
    - '/exit'

# Sistema de energia
energy:
  # Ativar o sistema de energia
  enabled: true
  # Quantia de energia por bloco quebrado
  amount: 1
  # Quantia de energia que irá aumentar a cada nível
  per-level: 1000
  # Ativar o sistema de dar encantamento aleatório
  give-enchant: true
  # Comandos que irá dar quando evoluir (com enchant)
  enchant-commands: []
  # Comandos que irá dar quando evoluir (sem enchant)
  no-enchant-commands: []
  # Enchants que poderão ser dados
  # chance,encantamento
  enchants:
    - '10.0,efficiency'
    - '10.0,nuclear'
    - '10.0,destructor'
    - '10.0,explosion'
    - '10.0,laser'
    - '10.0,drill'
    - '10.0,inverted-destructor'
    - '10.0,linear'
    - '10.0,sphere'
    - '10.0,x'
    - '10.0,fortune'
    - '10.0,summoner'
    - '10.0,speed'
    - '10.0,haste'
    - '10.0,lucky'
    - '10.0,multiplier'
    - '10.0,eletricity'
  # Mensagens
  enchant-evolved: |
    &r
    &bSua ferramenta evoluiu de nível!
    &bEncantamento adquirido: &f+1 nível de {enchantment}&b.
    &r
  no-enchant-evolved: |
    &r
    &bSua ferramenta evoluiu de nível!'
    &cInfelizmente todos seus encantamentos estão no máximo.'
    &r
  # Comandos que serão executados ao alcançar determinado nível
  # nível-necessário,cmd
  specific-rewards: [ '100,give {player} diamond 2' ]

# Sistema de encantamento aleatório por chance
random:
  chance: 0
  title: ''
  actionbar: ''
  chat: |
    &r
    &bEncantamento adquirido: &f+1 nível de {enchantment}&b.
    &r

# Enviar a mensagem de montantes ganhos a cada x tempo
earns-message:
  enabled: true
  # delay para enviar a mensagem
  # em segundos
  delay: 60
  chat-format: '&6&l|&f {provider_display}: &2{provider_symbol}&f{provider_value}'
  message: |
    &r
    &e&lGG! &eVocê quebrou &e&l{blocks}&e blocos no último minuto.
    &r
    &6Confira o lucro dos blocos quebrados:
    {chat}
    &r

# Item da ferramenta
tool:
  material: WOOD_AXE
  name: '&bMachado &6[{blocks_broken}]'
  lore:
    - '&7Inquebrável ∞'
    - '{enchants}'
    - ''
    - ' &fNível: &7{level}'
    - ' &fEnergia: &7{energy}/{energy_next} &f({progressbar}&f)'

# Item de folha ativável
leave:
  material: '1ba16c3890af39c3f2d576586cff443de07dad32b2315e2ff6f0d5d6a3c663dd'
  name: '&b+{amount} Folhas'
  lore:
    - ''
    - '&fQuantia: &b{amount}'
    - ''
    - '&7Clique com botão direito para ativar.'
    - ''
    - '&7Clique com shift + botão direito para compactar'
    - '&7todos os seus blocos no inventário em 1 só.'
    - ''

scoreboard:
  enabled: true
  title: '&b&lyStore'
  lines:
    - '&7     Área de Floresta'
    - ''
    - '&f B. quebrados: &7{blocks_broken}'
    - ''
    - '&e Machado'
    - '&8  ❘&f Nível: &7{level}'
    - '&8  ❘&f Energia: &7{energy}/{energy_next}'
    - ''
    - '&f Folhas: &e⛃{leaves}'
    - '&f Coins: &2$&a{money}'
    - ''
    - '&b    ystoreplugins.com.br'

# Itens padrões definidos para o jogador.
items:
  tool-slot: 2
  # Item utilizado para que o jogador saia da pesca.
  exit:
    material: 'BARRIER:0'
    slot: 8
    name: '&cSair da Ferramenta'
    lore:
      - '&7Clique para sair da'
      - '&7área de floresta.'
  # Item utilizado para que o jogador saia da pesca.
  classes:
    material: 'LEATHER_CHESTPLATE:0'
    slot: 6
    name: '&bClasses'
    lore:
      - ' &7As classes irão te dar mais'
      - ' &7chance e coins na floresta!'
      - ''
      - '&fSua classe: &7{classe}'
      - ''
      - '&aClique para upar sua classe'
  # Siga o exemplo abaixo para criar itens custom
  #custom:
  #  material: BARRIER:0
  #  slot: 0
  #  name: ''
  #  lore: []
  #  left-command: ''
  #  right-command: ''
  #  left-perm: 'yfloresta.left-perm.custom'
  #  right-perm: 'yfloresta.right-perm.custom'

# Configuração da barra de progresso
progress-bar:
  amount: 10
  symbol: ':'
  color-yes: '&a'
  color-no: '&7'

# Você pode criar quantos bônus quiser
# Será dado o bônus ao vender as platanções.
bonus:
  membros:
    order: 1
    # Permissão para ser reconhecido
    permission: 'yfloresta.bonus.membro'
    # Nome que irá aparecer nas mensagens
    display: '&7[Membro]'
    # Quantia do bônus em %
    bonus: 10.0
    bonus-leave: 10.0

# Sistema de anúncios ao chegar em um nível específico
specific-level:
  level10:
    # Nível necessário
    level: 10
    # Mensagem que será enviada
    message: |
      &r
      &c&lNÍVEL! &cO jogador &f{player} &cevoluiu para o nível &f&l{level}&c.
      &r