#        ____       _      _
#  _   _|  _ \ ___ | | ___| |_ __ _
# | | | | |_) / _ \| |/ _ \ __/ _` |
# | |_| |  _ < (_) | |  __/ || (_| |
#  \__, |_| \_\___/|_|\___|\__\__,_|
#  |___/

# *** ALERTA
# ESTE PLUGIN REQUER A OPÇÃO "packet-events" ATIVADA NO SEU yPlugins
# ***

#   __      _   _   _
#  / _\ ___| |_| |_(_)_ __   __ _ ___
#  \ \ / _ \ __| __| | '_ \ / _` / __|
#  _\ \  __/ |_| |_| | | | | (_| \__ \
#  \__/\___|\__|\__|_|_| |_|\__, |___/
#
# Sistemas principais.

# Sistemas gerais
general:
  # Mundos proibidos de colocar roletas
  world-blacklist: [ 'none' ]
