#         __  __ _                    _          _   _ _   _       _
#  _   _|  \/  (_)_ __   __ _ ___   / \   _ __ | |_(_) \ | |_   _| | _____ _ __
# | | | | |\/| | | '_ \ / _` / __| / _ \ | '_ \| __| |  \| | | | | |/ / _ \ '__|
# | |_| | |  | | | | | | (_| \__ \/ ___ \| | | | |_| | |\  | |_| |   <  __/ |
#  \__, |_|  |_|_|_| |_|\__,_|___/_/   \_\_| |_|\__|_|_| \_|\__,_|_|\_\___|_|
#  |___/
#
# Modo de depuração para correção de problemas no plugin.
debug-mode: false

#      ___      _        _
#     /   \__ _| |_ __ _| |__   __ _ ___  ___
#    / /\ / _` | __/ _` | '_ \ / _` / __|/ _ \
#   / /_// (_| | || (_| | |_) | (_| \__ \  __/
#  /___,' \__,_|\__\__,_|_.__/ \__,_|___/\___|
#
# Configurações do banco de dados.

database:
  # Determina o tipo de banco de dados. Valores válidos: [SQLITE, MYSQL, HIKARI (recomendado)]
  storage-type: SQLITE

  # Dados para conexão ao banco de dados MYSQL.
  data:
    # Endereço de conexão do banco de dados. [EX: 127.0.0.1]
    host: localhost
    # Porta de conexão do banco de dados. [EX: 3306]
    port: 3306
    # Nome do banco de dados a ser conectado. [EX: minecraft]
    database: ''
    # Usuário de conexão. [EX: root]
    username: ''
    # Senha do usuário de conexão: [EX: 123]
    password: ''

# Limite aceitável de blocos quebrados por checagem
limit: 25

# Limite de warns até executar o kick
warn-limit: 5

# Sistemas gerais do plugin
general:
  # Sistema de notificar o ganho de pontos
  discordhook:
    enabled: true
    channel: ''
    # Placeholders disponíveis:
    # {player}
    # {limit}
    embed: ''

actions:
  # Expulsar o jogador do servidor quando ultrapassar o limite
  kick: false
  # Avisar os staffs que tem um jogador com possível nuker (permissão: "yminasantinukeraddon.staff")
  warn: true

# Mensagens gerais
messages:
  kick: |

    &c&lANTI NUKER

    <s><s><s><s><s><s><s><s>&cVocê&f foi expulso do servidor por possível uso de nuker

    &eVocê ainda pode entrar no servidor, porém todos os staffs foram avisados.

  warn-logout: '&c&l[ANTI NUKER] &cO jogador &f{player} &cfoi expulso por estar quebrando &f{limit} blocos por segundo &cna área de mineração.'
  warn: '&c&l[ANTI NUKER] &cO jogador &f{player} &cestá quebrando &f{limit} blocos por segundo &cna área de mineração.'