#         __  __           _                  ____
#  _   _|  \/  |_   _ ___| |_ ___ _ __ _   _| __ )  _____  _____  ___
# | | | | |\/| | | | / __| __/ _ \ '__| | | |  _ \ / _ \ \/ / _ \/ __|
# | |_| | |  | | |_| \__ \ ||  __/ |  | |_| | |_) | (_) >  <  __/\__ \
#  \__, |_|  |_|\__, |___/\__\___|_|   \__, |____/ \___/_/\_\___||___/
#  |___/        |___/                  |___/
#

# Sistemas gerais
general:
  # Lista de vidros aleatórios
  random-glasses:
#    - 'STAINED_GLASS_PANE:0'
    - 'STAINED_GLASS_PANE:1'
    - 'STAINED_GLASS_PANE:2'
    - 'STAINED_GLASS_PANE:3'
    - 'STAINED_GLASS_PANE:4'
    - 'STAINED_GLASS_PANE:5'
    - 'STAINED_GLASS_PANE:6'
#    - 'STAINED_GLASS_PANE:7'
#    - 'STAINED_GLASS_PANE:8'
    - 'STAINED_GLASS_PANE:9'
    - 'STAINED_GLASS_PANE:10'
    - 'STAINED_GLASS_PANE:11'
#    - 'STAINED_GLASS_PANE:12'
    - 'STAINED_GLASS_PANE:13'
    - 'STAINED_GLASS_PANE:14'
#    - 'STAINED_GLASS_PANE:15'