# Comandos e aliases do plugin
Comando:
   Comando: 'caixamisteriosa'
   Aliases: [ mysterybox, mbox ]

# Opções gerais do plugin
Opcoes:
   # Ativar o sistema de animação
   Animacao: true

# Setas dos menus
Setas:
   Voltar:
      material: ARROW
      name: '&cVoltar'
      lore: [ '&7Clique para voltar ao menu anterior.' ]
   Anterior:
      material: ARROW
      name: '&cVoltar'
      lore: [ '&7Clique para voltar à página anterior.' ]
   Proximo:
      material: ARROW
      name: '&aPróxima'
      lore: [ '&7Clique para ir à próxima página.' ]