#          ____
#  _   _ / ___|__ _ _ __ ___  _ __   ___
# | | | | |   / _` | '_ ` _ \| '_ \ / _ \
# | |_| | |__| (_| | | | | | | |_) | (_) |
#  \__, |\____\__,_|_| |_| |_| .__/ \___/
#  |___/                     |_|
#
# Discord: discord.ystoreplugins.com.br
# Site: ystoreplugins.com.br
#

# Modo de depuração para correção de problemas no plugin.
debug-mode: false

#      ___      _        _
#     /   \__ _| |_ __ _| |__   __ _ ___  ___
#    / /\ / _` | __/ _` | '_ \ / _` / __|/ _ \
#   / /_// (_| | || (_| | |_) | (_| \__ \  __/
#  /___,' \__,_|\__\__,_|_.__/ \__,_|___/\___|
#
# Configurações do banco de dados.

database:
  # Determina o tipo de banco de dados. Valores válidos: [SQLITE, MYSQL, HIKARI (recomendado)]
  storage-type: SQLITE

  # Dados para conexão ao banco de dados MYSQL.
  data:
    # Endereço de conexão do banco de dados. [EX: 127.0.0.1]
    host: localhost
    # Porta de conexão do banco de dados. [EX: 3306]
    port: 3306
    # Nome do banco de dados a ser conectado. [EX: minecraft]
    database: ''
    # Usuário de conexão. [EX: root]
    username: ''
    # Senha do usuário de conexão: [EX: 123]
    password: ''

#   __      _   _   _
#  / _\ ___| |_| |_(_)_ __   __ _ ___
#  \ \ / _ \ __| __| | '_ \ / _` / __|
#  _\ \  __/ |_| |_| | | | | (_| \__ \
#  \__/\___|\__|\__|_|_| |_|\__, |___/
#
# Sistemas principais.

# Sistemas gerais
general:
  # Delay para checagem da notificação de pagamento (automático)
  # Em segundos
  notification-delay: 10
  # Delay para checagem da notificação de pagamento (manual)
  # Em segundos
  manual-delay: 30
  # Embed do yDiscorHook para enviar a cobrança no privado
  dm-charge-embed: 'ypayments_private'
  # Tempo para enviar a mensagem de alerta de coleta
  # em minutos
  alert-message-time: 600

# Configuração do mercado-pago
mercado-pago:
  secret: ''
  id: ''
  notification-url: 'https://ystoreteste.000webhostapp.com/notification_mp.php'

# Configuração do picpay
picpay:
  picpay-token: ''
  seller-token: ''
  notification-url: 'https://ystoreteste.000webhostapp.com/notification_picpay.php'

# Configuração do paypal
paypal:
  email: ''
  notification-url: 'https://ystoreteste.000webhostapp.com/notification_paypal.php'

# Configuração do coinbase
coinbase:
  version: '2018-03-22'
  api-key: ''

# Configuração do Stripe
stripe:
  secret-key: ''
  success-url: 'https://ystoreplugins.com.br'

# Configuração do short.io
# Utilizado para encurtar o link do paypal
short-io:
  enabled: true
  # Deixe vazio para usar o da yStore
  secret-key: ''
  # Deixe vazio para usar o da yStore
  domain: ''

# Sistema de npc
npc:
  skin: 'Pitombaa'
  hologram:
    offset: 3.4
    hologram:
      - '&6&lLOJA VIRTUAL'
      - '&7Seu site agora ingame!'
      - '[item]EMERALD'

# Sistema de lores
lores:
  map:
    - ''
    - ' &fGerado em: &7{date} às {hour}'
    - ' &fProduto: &b{product}'
    - ' &fReferência: &b{reference}'
    - ''
  transaction-not-completed:
    - ''
    - ' &aBotão &fESQUERDO &apara atualizar.'
    - ' &aBotão &fDIREITO &apara pegar o mapa.'
    - ''

# Sistema de status
status:
  approved: '&aAprovado'
  processing: '&bProcessando...'
  pending: '&ePendente...'
  canceled: '&cCancelado'
  refunded: '&cReembolsado'
  in-mediation: '&dEm mediação...'