#        ____                   _
#  _   _| __ )  ___  ___ ___   / \   _ __ ___ _ __   __ _
# | | | |  _ \ / _ \/ __/ __| / _ \ | '__/ _ \ '_ \ / _` |
# | |_| | |_) | (_) \__ \__ \/ ___ \| | |  __/ | | | (_| |
#  \__, |____/ \___/|___/___/_/   \_\_|  \___|_| |_|\__,_|
#  |___/
# Discord: discord.ystoreplugins.com.br
# Site: ystoreplugins.com.br
#

# Modo de depuração para correção de problemas no plugin.
debug-mode: false

#      ___      _        _
#     /   \__ _| |_ __ _| |__   __ _ ___  ___
#    / /\ / _` | __/ _` | '_ \ / _` / __|/ _ \
#   / /_// (_| | || (_| | |_) | (_| \__ \  __/
#  /___,' \__,_|\__\__,_|_.__/ \__,_|___/\___|
#
# Configurações do banco de dados.

database:
  # Determina o tipo de banco de dados. Valores válidos: [SQLITE, MYSQL, HIKARI (recomendado)]
  storage-type: SQLITE

  # Dados para conexão ao banco de dados MYSQL.
  data:
    # Endereço de conexão do banco de dados. [EX: 127.0.0.1]
    host: localhost
    # Porta de conexão do banco de dados. [EX: 3306]
    port: 3306
    # Nome do banco de dados a ser conectado. [EX: minecraft]
    database: ''
    # Usuário de conexão. [EX: root]
    username: ''
    # Senha do usuário de conexão: [EX: 123]
    password: ''

#   __      _   _   _
#  / _\ ___| |_| |_(_)_ __   __ _ ___
#  \ \ / _ \ __| __| | '_ \ / _` / __|
#  _\ \  __/ |_| |_| | | | | (_| \__ \
#  \__/\___|\__|\__|_|_| |_|\__, |___/
#
# Sistemas principais.

# Delay para carregar os dados depois do login
# Necessário para usar em servidor de mina separado
# Recomendado: 20 ticks
login-delay: 20
# Este limite serve para recolher recompensas
# Desativar ou aumentar o limite pode gerar lag
# e em alguns casos crashar o servidor.
limit:
  enabled: true
  # Máximo que irá recolher por vez
  max: 1000

# Raio de checagem de mesmo boss existente
radius: 5

# Delay para hitar os bosses
# Deixe 0 para não usar
# em millisegundos
hit-delay: 500

# Redução de dano caso o jogador tenha protection na armadura
damage-protection:
  # Encantamento que será reconhecido
  enchantment: 'PROTECTION_ENVIRONMENTAL'
  # Quantidade de itens de armaduras que poderão somar na redução
  amount: 1
  # Nível, quantidade de dano que será reduzido
  levels:
    - '1,1.0'
    - '5,2.0'
    - '10,3.0'

# Sistema de spawnar bosses em horários definidos
auto-spawn:
  horario1:
    # nome do arquivo do boss sem o .yml
    boss: ''
    # todos, segunda, terca, quarta, quinta, sexta, sabado, domingo
    # dia-hora-minuto-segundo
    time: 'todos-00:00:01'

# Sistema de amuletos
amulets:
  anti-damage:
    material: 'dd9850f0a95937be428d96e7b6f8a3e28d68afd5a688568b6936a44085639386'
    name: '&cBloquear dano'
    lore:
      - ''
      - '&7Este amuleto permite que você não'
      - '&7sofra dano dos bosses.'
      - ''
      - '&aClique para ativar'
  anti-knockback:
    material: '61a9ae9db36f70d467354069fbbdcc7d279baf6721561381da60d339b23d8829'
    name: '&cBloquear KnockBack'
    lore:
      - ''
      - '&7Este amuleto permite que você não'
      - '&7sofra knockback dos bosses.'
      - ''
      - '&aClique para ativar'
  anti-fire:
    material: '311e2e8f23609001106c07f1697a5a032646a85de8227033d33caab8c12c5e92'
    name: '&cBloquear fogo'
    lore:
      - ''
      - '&7Este amuleto permite que você não'
      - '&7receba fogo dos bosses.'
      - ''
      - '&aClique para ativar'

# Configuração da barra de progresso
progress-bar:
  amount: 10
  symbol: ':'
  color-yes: '&a'
  color-no: '&7'

# Sistema de lores
lore:
  chance: ['', '&6Chance: &f{chance}%', '']

# Sistema de formatos de money e quantia
format:
  type: 'LETTER' # Tipos: LETTER - NUMBER
  max-decimals: 4
  formats:
    - ''
    - ''
    - 'K'
    - 'M'
    - 'B'
    - 'T'
    - 'Q'
    - 'QQ'
    - 'S'
    - 'SS'
    - 'O'
    - 'N'
    - 'D'