#         ____  _             _    ____
#  _   _/ ___|| |_ __ _  ___| | _| __ )  ___  ___ ___  ___  ___
# | | | \___ \| __/ _` |/ __| |/ /  _ \ / _ \/ __/ __|/ _ \/ __|
# | |_| |___) | || (_| | (__|   <| |_) | (_) \__ \__ \  __/\__ \
#  \__, |____/ \__\__,_|\___|_|\_\____/ \___/|___/___/\___||___/
#  |___/
# Discord: discord.ystoreplugins.com.br
# Site: ystoreplugins.com.br
#

# Modo de depuração para correção de problemas no plugin.
debug-mode: false

#      ___      _        _
#     /   \__ _| |_ __ _| |__   __ _ ___  ___
#    / /\ / _` | __/ _` | '_ \ / _` / __|/ _ \
#   / /_// (_| | || (_| | |_) | (_| \__ \  __/
#  /___,' \__,_|\__\__,_|_.__/ \__,_|___/\___|
#
# Configurações do banco de dados.

database:
  # Determina o tipo de banco de dados. Valores válidos: [SQLITE, MYSQL, HIKARI (recomendado)]
  storage-type: SQLITE

  # Dados para conexão ao banco de dados MYSQL.
  data:
    # Endereço de conexão do banco de dados. [EX: 127.0.0.1]
    host: localhost
    # Porta de conexão do banco de dados. [EX: 3306]
    port: 3306
    # Nome do banco de dados a ser conectado. [EX: minecraft]
    database: ''
    # Usuário de conexão. [EX: root]
    username: ''
    # Senha do usuário de conexão: [EX: 123]
    password: ''

#   __      _   _   _
#  / _\ ___| |_| |_(_)_ __   __ _ ___
#  \ \ / _ \ __| __| | '_ \ / _` / __|
#  _\ \  __/ |_| |_| | | | | (_| \__ \
#  \__/\___|\__|\__|_|_| |_|\__, |___/
#
# Sistemas principais.

# Delay para carregar os dados depois do login
# Necessário para usar em servidor de mina separado
# Recomendado: 20 ticks
login-delay: 20
# Este limite serve para recolher recompensas
# Desativar ou aumentar o limite pode gerar lag
# e em alguns casos crashar o servidor.
limit:
  enabled: true
  # Máximo que irá recolher por vez
  max: 1000

# Sistemas gerais
general:
  # Habilitar o sistema de stack-bosses
  stack: true
  # Permitir colocar bosses e matar bosses apenas nos plots
  plot: false
  # Verifica se há mobs (ou outros bosses) por perto antes de spawnar
  # Raio em blocos.
  radius: 5
  # Delay para hitar os bosses
  # Deixe 0 para não usar
  # em millisegundos
  hit-delay: 500
  # Mundos bloqueados para colocar bosses
  world-blacklist: [ 'none' ]
  # Matar todos no shift
  shift-all: false
  # Matar todos sem shift
  no-shift-all: false
  # Quantia máxima que poderá matar
  # Cuidado com valores altos
  # -1 para infinito
  kill-maximum: 1000
  # Deletar a recompensa ao clicar com botão direito
  right-delete-reward: true
  # Blacklist de entidades que não serão verificadas no raio de "Mobs por perto"
  nearby-entity-blacklist: [ 'PLAYER', 'DROPPED_ITEM', 'ARROW', 'SPLASH_POTION', 'EXPERIENCE_ORB', 'THROWN_EXP_BOTTLE', 'SNOWBALL', 'EGG', 'ITEM' ]
  # Blacklist de metadata que não serão verificadas no raio de "Mobs por perto"
  nearby-metadata-blacklist: [ 'mascote' ]

effects:
  explosion:
    # Lista da 1.8: https://helpch.at/docs/1.8/org/bukkit/Sound.html
    # Lista da 1.16: https://helpch.at/docs/1.16.2/org/bukkit/Sound.html
    # Lista da 1.18: https://helpch.at/docs/1.18/org/bukkit/Sound.html
    sound: 'EXPLODE'
    # Lista da 1.8: https://helpch.at/docs/1.8/org/bukkit/Effect.html
    # Lista da 1.16: https://helpch.at/docs/1.16.2/org/bukkit/Effect.html
    # Lista da 1.18: https://helpch.at/docs/1.18/org/bukkit/Effect.html
    particle1: 'LAVA'
    particle2: 'VILLAGER_ANGRY'
    particle3: 'CLOUD'
  # Lista da 1.8: https://helpch.at/docs/1.8/org/bukkit/potion/PotionEffectType.html
  # Lista da 1.16: https://helpch.at/docs/1.16.2/org/bukkit/potion/PotionEffectType.html
  # Lista da 1.18: https://helpch.at/docs/1.18/org/bukkit/potion/PotionEffectType.html
  poison: 'POISON'
  confusion: 'CONFUSION'
  blindness: 'BLINDNESS'

# Sistema de lores
lore:
  chance: ['', '&6Chance: &f{chance}%', '']

# Configuração da barra de progresso
progress-bar:
  amount: 10
  symbol: ':'
  color-yes: '&a'
  color-no: '&7'

# Livro do encantamento damage
damage:
  # Mensagens
  give-book: '&bVocê deu &71x Livro de Dano {damage}&b para o jogador &f{player}.'
  received-book: '&bVocê recebeu &71x Livro de Dano {damage}&b.'
  maximum: '&cVocê não pode encantar esta espada, pois ela já está no máximo, com {damage} em Dano.'
  converted: '&bVocê compactou todos seus livros em 1.'
  # Item da sharpness ativável
  usable-item:
    material: ENCHANTED_BOOK
    name: '&b+{damage} Dano'
    lore:
      - ''
      - '&fDano: &b{damage}'
      - ''
      - '&7Clique em uma matadora para ativar.'

# Livro do encantamento damage
stack:
  # Mensagens
  give-book: '&bVocê deu &71x Livro de Kill-Stack {stack}&b para o jogador &f{player}.'
  received-book: '&bVocê recebeu &71x Livro de Kill-Stack {stack}&b.'
  maximum: '&cVocê não pode encantar esta espada, pois ela já está no máximo, com {stack} em Kill-Stack.'
  converted: '&bVocê compactou todos seus livros em 1.'
  # Item da sharpness ativável
  usable-item:
    material: ENCHANTED_BOOK
    name: '&b+{stack} Kill-Stack'
    lore:
      - ''
      - '&fKill-Stack: &b{stack}'
      - ''
      - '&7Clique em uma matadora para ativar.'