#         ____ _                  ____      _                   _       _     _
#  _   _ / ___| | __ _ _ __  ___ / ___|___ | | ___  _ __ ___   / \   __| | __| | ___  _ __
# | | | | |   | |/ _` | '_ \/ __| |   / _ \| |/ _ \| '__/ __| / _ \ / _` |/ _` |/ _ \| '_ \
# | |_| | |___| | (_| | | | \__ \ |__| (_) | | (_) | |  \__ \/ ___ \ (_| | (_| | (_) | | | |
#  \__, |\____|_|\__,_|_| |_|___/\____\___/|_|\___/|_|  |___/_/   \_\__,_|\__,_|\___/|_| |_|
#  |___/
#

# Formatação da placeholder (RELATIVE)
# Para testes, use o comando "/papi parserel <player> <player> %rel_yclanscolorsaddon_color%TESTE"
#
# PLACEHOLDER: %rel_yclanscolorsaddon_color%
#
placeholders:
  no-clan: '&7'
  same-clan: '&a'
  clan-ally: '&2[A] &a'
  clan-neutral: '&c'
  clan-rival: '&4[R] &c'