Maximo: 0 #o máximo do minecraft é 30k
Ativar blocos: true
Ativar mobs: true
Ativar pesca: true
Ativar tradutor: false #ele irá remover o nome dos outros enchants e irá mostrar apenas do looting

Comando:
   Comando: 'givelooting'
   Aliases: {}

Pesca:
   Chance: 100.0
   Quantia: 100 #quantia de looting

# Mundos onde não receberá looting
Mundo blacklist:
   - 'none'

Permitidos:
- 'DIAMOND_SWORD'
- 'IRON_SWORD'
- 'GOLD_SWORD'
- 'STONE_SWORD'
- 'WOOD_SWORD'

Item:
   CustomSkull: false
   URL: ''
   ID: 388
   Data: 0
   Glow: true
   Name: '&eLooting'
   Lore:
   - '&7Looting: {lvl}'
   - ''
   - '&7Este encantamento permite multiplicar seus drops.'
   - '&7Clique no seu item para encantar.'
   - '&7Compatível com Espadas.'
   - ''
   - '&7Shift+Botão direito junta suas lootings em 1.'

Mensagens:
   Encantou: '&a&lSUCESSO! &aVocê encantou seu item com looting &7{lvl}&a.'
   Nao compativel: '&c&lERRO! &cEste item não é compatível com este encantamento.'
   Maximo: '&c&lERRO! &cSeu item já alcançou o máximo de looting.'
   Permissao: '&c&lERRO! &cVocê não tem permissão para usar isto.'
   Numero: '&c&lERRO! &cA quantia deve ser um número.'
   Numero max: '&c&lERRO! &cO máximo permitido é &7{max}&c.'
   Nao encontrado: '&c&lERRO! &cJogador não encontrado.'
   Deu: '&a&lSUCESSO! &aVocê deu &7{lvl} &ade looting para o jogador &7{player}&a.'
   Recebeu: '&a&lSUCESSO! &aVocê recebeu &7{lvl} &ade looting.'
   Converteu: '&a&lSUCESSO! &aVocê converteu seus lootings em &71&a.'
   Title:
      Ativar: true
      Title: '&aVocê ganhou'
      Subtitle: '&7{lvl}&a de looting'
   Chat:
      Ativar: true
      Msg:
      - ''
      - '&aVocê ganhou &7{lvl} &aem looting.'
      - ''
      
Formats:
 - ''
 - ''
 - 'K'
 - 'M'
 - 'B'